version: '3'

services:
  postgres_bd:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=IdNotepad
    volumes:
      - ./pgdata:/data/postgres

  api:
    build: .
    image: node
    restart: always
    container_name: node
    ports:
      - 3333:3333
    volumes:
      - .:/usr/api
    depends_on:
      - postgres_bd
